baseURL = 'https://abstractionjackson.com/'
languageCode = 'en-us'
title = 'Abstraction Jackson'

summaryLength = 0

[security.exec]
allow = [
  '^(dart-)?sass(-embedded)?$',
  '^go$',
  '^git$',
  '^npx$',
  '^postcss$',
  '^tailwindcss$',
  '^emacs$',
]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[[menus.main]]
name = 'Portfolio'
pageRef = '/portfolio'
weight = 10
[[menus.main]]
name = "About"
pageRef = "/about"
weight = 15


[params]
[params.social]
GitHub = "https://github.com/abstractionjackson"
LinkedIn = "https://linkedin.com/in/jacksongalan"
