baseURL = 'https://abstractionjackson.com/'
languageCode = 'en-us'
title = 'Abstraction Jackson'

[security.exec]
allow = [
  '^(dart-)?sass(-embedded)?$',
  '^go$',
  '^git$',
  '^npx$',
  '^postcss$',
  '^tailwindcss$',
  '^emacs$',
]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[menus]
[[menus.main]]
name = 'Archive'
pageRef = '/archive'
weight = 30

[[menus.main]]
name = 'Portfolio'
pageRef = '/portfolio'
weight = 10

[[menus.main]]
name = 'Notes'
pageRef = '/note'
weight = 15

# [[menus.main]]
# name = 'Sketches'
# pageRef = '/sketch'
# weight = 99

[params]
[params.social]
GitHub = "https://github.com/abstractionjackson"
LinkedIn = "https://linkedin.com/in/jacksongalan"
