

[menus]
  [[menus.main]]
    name = 'Archive'
    pageRef = '/post'
    weight = 10

  [[menus.main]]
    name = 'Portfolio'
    pageRef = '/categories/portfolio'
    weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
